# Generated by Django 2.2.4 on 2019-08-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190812_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_users',
            field=models.ManyToManyField(related_name='people', through='users.GroupMember', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, related_name='people', through='users.GroupMember', to='users.Group'),
        ),
    ]
